### ISSUE TITLE
Allow deserializing dependencies inline

### ISSUE THREAD

**Issue by paulwrubel** [paulwrubel/luxide#15]
This is more complicated and definitely less efficient, but a "nice-to-have" for certain scenarios, especially when you know a specific texture will only be given to specific material, or material to a geometric, etc.

Without inlining:
```yaml
...
geometrics:
  raspberry_blush_sphere: !sphere
    center: [0, 0, 0]
    radius: 1
    material: lambertian_raspberry_blush

materials:
  lambertian_raspberry_blush: !lambertian
    reflectance_texture: solid_color_raspberry_blush
    emittance_texture: solid_color_black

textures:
  solid_color_raspberry_blush: !solid_color [0.82353, 0.37255, 0.34118]
  solid_color_black: !solid_color [0, 0, 0]
...
```

With inlining:
```yaml
...
geometrics:
  raspberry_blush_sphere: !sphere
    center: [0, 0, 0]
    radius: 1
    material: !lambertian
      reflectance_texture: !solid_color [0.82353, 0.37255, 0.34118]
      emittance_texture: !solid_color [0, 0, 0]
...
```
